### ISSUE TITLE
need to verify write permissions of local destination folder prior to transfer

### ISSUE THREAD

**Issue by ipmonk** [Juniper/splitcopy#8]
// when run on *nix

```
Traceback (most recent call last):
  File "/Users/foobar/tmp/bin/splitcopy", line 8, in <module>
    sys.exit(main())
  File "/Users/foobar/tmp/lib/python3.10/site-packages/splitcopy/splitcopy.py", line 222, in main
    loop_start, loop_end = splitcopyget.get()
  File "/Users/foobar/tmp/lib/python3.10/site-packages/splitcopy/get.py", line 215, in get
    self.join_files_local()
  File "/Users/foobar/tmp/lib/python3.10/site-packages/splitcopy/get.py", line 681, in join_files_local
    with open(dst_file, "wb") as dst:
PermissionError: [Errno 13] Permission denied: '/Users/foobar/tmp/perm_denied/v6_linklocal_isis_db'
```

// when run on windows

```
Traceback (most recent call last):
  File "C:\Users\foobar\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\foobar\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "c:\Users\foobar\juniper\Scripts\splitcopy.exe\__main__.py", line 7, in <module>
  File "c:\Users\foobar\juniper\lib\site-packages\splitcopy\splitcopy.py", line 222, in main
    loop_start, loop_end = splitcopyget.get()
  File "c:\Users\foobar\juniper\lib\site-packages\splitcopy\get.py", line 215, in get
    self.join_files_local()
  File "c:\Users\foobar\juniper\lib\site-packages\splitcopy\get.py", line 681, in join_files_local
    with open(dst_file, "wb") as dst:
PermissionError: [Errno 13] Permission denied: 'c:\\\\bigfile'
```

**Comment by ipmonk** [comment]
resolved by commit 72c94e2
